namespace: web-crawler
urlFetcher:
  deploymentName: url-fetcher
  queueName: url-queue
  queueLength: "100"
  minReplicas: 1
  maxReplicas: 5
contentParser:
  deploymentName: content-parser
  queueName: parse-queue
  queueLength: "200"
  minReplicas: 1
  maxReplicas: 3
