apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: content-parser-scaler
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.contentParser.deploymentName }}
  minReplicaCount: {{ .Values.contentParser.minReplicas }}
  maxReplicaCount: {{ .Values.contentParser.maxReplicas }}
  triggers:
    - type: azure-queue
      metadata:
        queueName: {{ .Values.contentParser.queueName }}
        queueLength: {{ .Values.contentParser.queueLength | quote }}
        connectionFromEnv: AZURE_STORAGE_CONNECTION_STRING
