apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: url-fetcher-scaler
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.urlFetcher.deploymentName }}
  minReplicaCount: {{ .Values.urlFetcher.minReplicas }}
  maxReplicaCount: {{ .Values.urlFetcher.maxReplicas }}
  triggers:
    - type: azure-queue
      metadata:
        queueName: {{ .Values.urlFetcher.queueName }}
        queueLength: {{ .Values.urlFetcher.queueLength | quote }}
        connectionFromEnv: AZURE_STORAGE_CONNECTION_STRING
