output "cluster_id" {
  description = "ID of the AKS cluster."
  value       = azurerm_kubernetes_cluster.this.id
}

output "cluster_name" {
  description = "Name of the AKS cluster."
  value       = azurerm_kubernetes_cluster.this.name
}

output "kube_config" {
  description = "Parsed kubeconfig block for the AKS cluster."
  value       = azurerm_kubernetes_cluster.this.kube_config[0]
  sensitive   = true
}

output "kube_config_raw" {
  description = "Raw kubeconfig generated by the AKS cluster."
  value       = azurerm_kubernetes_cluster.this.kube_config_raw
  sensitive   = true
}

output "host" {
  description = "Kubernetes API server host for the AKS cluster."
  value       = azurerm_kubernetes_cluster.this.kube_config[0].host
}

output "client_certificate" {
  description = "Decoded client certificate for Kubernetes authentication."
  value       = base64decode(azurerm_kubernetes_cluster.this.kube_config[0].client_certificate)
  sensitive   = true
}

output "client_key" {
  description = "Decoded client key for Kubernetes authentication."
  value       = base64decode(azurerm_kubernetes_cluster.this.kube_config[0].client_key)
  sensitive   = true
}

output "cluster_ca_certificate" {
  description = "Decoded cluster CA certificate for Kubernetes authentication."
  value       = base64decode(azurerm_kubernetes_cluster.this.kube_config[0].cluster_ca_certificate)
  sensitive   = true
}

output "principal_id" {
  description = "Principal ID of the AKS managed identity."
  value       = azurerm_kubernetes_cluster.this.identity[0].principal_id
}
