output "resource_group_name" {
  description = "Name of the Azure resource group containing the deployment."
  value       = azurerm_resource_group.this.name
}

output "aks_cluster_name" {
  description = "Name of the AKS cluster."
  value       = module.aks.cluster_name
}

output "storage_account_name" {
  description = "Name of the Azure Storage account."
  value       = module.storage.storage_account_name
}

output "public_ip_address" {
  description = "Public IP address reserved for ingress traffic."
  value       = module.networking.public_ip_address
}

output "kube_config" {
  description = "Raw kubeconfig generated by the AKS cluster."
  value       = module.aks.kube_config_raw
  sensitive   = true
}
